services:
  php:
    container_name: api-platform-3
    build:
      context: '.'
      target: frankenphp_dev
      args:
        DDE_UID: ${DDE_UID}
        DDE_GID: ${DDE_GID}
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: api-platform-3.test, api.api-platform-3.test
      SSH_AUTH_SOCK: /tmp/ssh-agent/socket
      CADDY_GLOBAL_OPTIONS: debug
      SERVER_NAME: ${SERVER_NAME:-localhost}, php:80
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      # Run "composer require symfony/mercure-bundle" to install and configure the Mercure integration
      MERCURE_URL: ${CADDY_MERCURE_URL:-http://php/.well-known/mercure}
      MERCURE_PUBLIC_URL: ${CADDY_MERCURE_PUBLIC_URL:-https://${SERVER_NAME:-localhost}:${HTTPS_PORT:-443}/.well-known/mercure}
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      # The two next lines can be removed after initial installation
      SYMFONY_VERSION: ${SYMFONY_VERSION:-}
      STABILITY: ${STABILITY:-stable}
    volumes:
      - /var/www/var
      - caddy_data:/data
      - caddy_config:/config
      - ./:/var/www/:cached
      - ./var/data:/var/www/var/data:cached
      - ssh-agent_socket-dir:/tmp/ssh-agent:ro
    hostname: api    
    domainname: api-platform-3.test
  
volumes:
  codegen-schema: ~
  ssh-agent_socket-dir:
    name: dde_ssh-agent_socket-dir
    external: true
  caddy_data:
  caddy_config:

networks:
  default:
    name: 'dde'
    external: true
